name: 연금복권 구매
on:
  # schedule:
  #   - cron: '0 1 * * 0'
  workflow_dispatch:
    inputs:
      smoke:
        type: 'choice'
        description: '실제 구매는 하지 않고 동작 확인만 수행'
        required: true
        options:
          - 'true'
          - 'false'
        default: 'true'
jobs:
  buy-lottery:
    timeout-minutes: 5
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install -g yarn && yarn
      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps
      - name: Run
        env:
          USER_ID: ${{ secrets.ID }}
          USER_PW: ${{ secrets.PASSWORD }}
          SMOKE: ${{ inputs.smoke || 'false' }}
        run: yarn ci -g pension
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7
