name: Buy lotto
on:
  schedule:
    - cron: "0 10 * * 5"
  workflow_dispatch:
    inputs:
      amount: 
        type: "choice"
        description: "복권 구매 수량"
        required: true
        options:
          - "1"
          - "2"
          - "3"
          - "4"
          - "5"
        default: "5"
      smoke:
        type: "choice"
        description: "실제 구매는 하지 않고 동작 확인만 수행"
        required: true
        options:
          - "true"
          - "false"
        default: "true"
jobs:
  buy-lotto:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm install -g yarn && yarn
    - name: Install Playwright Browsers
      run: yarn playwright install --with-deps
    - name: Run
      env:
        USER_ID: ${{ secrets.ID }}
        USER_PW: ${{ secrets.PASSWORD }}
        AMOUNT: ${{ inputs.amount || '5' }}
        SMOKE: ${{ inputs.smoke || 'false' }}
      run: yarn ci
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 7
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: trace
        path: test-results
        retention-days: 7
